services:
  - type: web
    name: batiklens-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app_mobilenet:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
